### PR TITLE
config file turn off debug

### PR DESCRIPTION
**Pull request by jordan2lee**
added skeleton for host, port,dev values in `config.yaml` and hardcoded to use the `staging` values. likely long-term want to change from hardcoded to a command or environment.

### CODE REVIEW

**Comment by jordan2lee** [comment]
also note that in the config file the `host` and `port` should allow for remapping from localhost. another helpful link https://dash.plotly.com/dash-enterprise/map-local-directories

**Comment by kellrott** [comment]
How about getting the stage with an environmental variable, and then using that to select the correct config section from the main config file:

```
STAGE = os.environ.get("BMEG_STAGE", "DEV")

app.run_server(
        host=config[STAGE]['host'],
        debug=config[STAGE]['dev'],
        port=config[STAGE]['port']
    )
```

**Comment by jordan2lee** [comment]
works for `DEV` but returns warnings for `PROD`

**Comment by kellrott** [comment]
LGTM

**Pull request merged**
