### PR TITLE
expand snakelike-build branch

### PR DESCRIPTION
**Pull request by jordan2lee**
added sample characteristics dropdown and linked to umap. colored by characteristics. characteristics calculated as user selects. minor tweaks

this `sample_char` was branched from the PR #48  (that had fixed massive flake8 issues not present on other branches). this was done to avoid >50 conflicts when #48 merged to `main`

### CODE REVIEW

**Comment by jordan2lee** [comment]
related to Issue #42

**Comment by kellrott** [comment]
For the TCGA cases, the sample can be either tumor or normal. That is held at the sample level, not the case level. Currently the query `q = G.query().V(list(df.index)).out("case").as_('c').render([prop])` only looks at the case level. To include a second possible query for sample level features?

**Comment by kellrott** [comment]
The table name in the scatter plot never changes, it's always 'Characteristics'. It should change to reflect the selected characteristic.

**Comment by jordan2lee** [comment]
> The table name in the scatter plot never changes, it's always 'Characteristics'. It should change to reflect the selected characteristic.

Fixed in commit 61f72fb

**Comment by jordan2lee** [comment]
> For the TCGA cases, the sample can be either tumor or normal. That is held at the sample level, not the case level. Currently the query `q = G.query().V(list(df.index)).out("case").as_('c').render([prop])` only looks at the case level. To include a second possible query for sample level features?

added feature in commit 41a365d

**Pull request merged**
